apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: reporting-dashboard
spec:
  selector:
    matchLabels:
      app: pmoDashboard
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: pmoDashboard
    spec:
      containers:
      - name: pmo-dashboard
        image: gchanchal/gauravs:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-dashboard
  labels:
    run: pmoDashboard
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: pmoDashboard
  type: NodePort
