apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: oscar-django-deployment
  labels:
    app: django
    component: oscar
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels: 
        app: django
        component: oscar
        tier: frontend
    spec:
      containers:
        - name: oscar-django
          image: michaelatnutanix/oscar_jet:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: DATABASE_HOST
              value: postgres-service

            - name: DATABASE_NAME
              value: "oscar_django"

            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: object-credentials
                  key: access

            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: object-credentials
                  key: secret

            - name: STATIC_BUCKET
              value: "oscarstatic"

            - name: S3_ENDPOINT_URL
              value: "http://10.4.222.151:7200/"
